name: Trigger auto deployment for webcv-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/webcv-frontend-AutoDeployTrigger-ca85b103-d282-4836-85f2-5c5086b5f65e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WEBCVFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBCVFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBCVFRONTEND_AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          containerAppName: webcv-frontend
          resourceGroup: webcv-ai
          imageToBuild: ghcr.io/${{ github.repository }}:${{ github.sha }}


